Disable MEDIA_CONFERENCE_ID validation, api now also supports acronym
voc/hls-relive pull request #2
Opened 2018-10-06 20:23 UTC by saerdnaer

Since PR https://github.com/voc/voctoweb/pull/269 the voctoweb public API also supports conference lookup via acronym, additional to voctoweb's local conference id. This documented with https://github.com/voc/voctoweb/commit/f4834b00244465f7057187198b615986ed28024f

2018-10-07 11:25 UTC, florolf requested changes
Please provide a proper commit message (see https://who-t.blogspot.com/2009/12/on-commit-messages.html for some guidelines).

@manno: This will change the data type of the `media_conference_id` field in the `index.json` media consumes. Would this require changes on your end?

2018-10-07 11:50 UTC, manno commented
@florolf going from int to string is fine

2018-10-07 19:24 UTC, saerdnaer commented
@florolf updated title + description, use Github's "Squash and merge" button to get a clean commit or simply update your review.

2018-11-01 18:21 UTC, closed without merging

2018-11-01 18:22 UTC, florolf commented
Merged, thanks.